# Created using wingetcreate 1.6.5.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: STYInc.STY1001.UnowhyTools
PackageVersion: "31.04"
InstallerType: exe
InstallerSwitches:
  Silent: -s
UnsupportedOSArchitectures:
- x86
- arm
- arm64
ElevationRequirement: elevationRequired
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/STY1001/Unowhy-Tools/releases/download/v31.04/Unowhy.Tools.31.04.Installer.exe
  InstallerSha256: 2DE21D6D0A1AA90F6E4FD89EE7A2982BFA828653888BEFADF01AA9A54A325FC1
ManifestType: installer
ManifestVersion: 1.6.0
ReleaseDate: 2025-06-24
